site_name: Sensor Web Tutorial


# Documentation and theme
theme:
  name: readthedocs
  feature:
    tabs: false
    
markdown_extensions:
  - attr_list
  - admonition
  - codehilite:
      linenums: true
      guess_lang: false
  - footnotes
  - markdown_include.include:
      base_path: docs
  - meta
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      permalink: true

nav:
  - index.md
  - 01_sdis-and-swe.md
  - 02_swe-overview.md
  - 03_sensorml.md
  - 04_o-and-m.md
  - 05_web-services.md
  - 06_sos-setup.md
  - 07_client-software.md
  - 08_iot.md
  
  - "Hands-On":
    - hands-on/09_00_hands-on.md
    - hands-on/09_01_sos_installation_war_file.md
    - hands-on/09_02_sos_admin_interface.md
    - hands-on/09_03_sos_example_request.md
    - hands-on/09_04_advanced_sos_example_request.md
    - hands-on/09_05_sta_installation_war_file.md
    - hands-on/09_06_sta_example_request.md
    - hands-on/09_07_helgoland_client.md
    - hands-on/09_08_sos_importer.md
  - 89_installation_requirements_for_windows.md
  - 99_bibliography.md